/*
 * TinyQEDI2CCMD.h
 *
 * Created: 01/05/2015 23:46:55
 *  Author: bd59
 */ 


#ifndef TINYQEDI2CCMD_H_
#define TINYQEDI2CCMD_H_

#define I2CCMD_RESET_COUNTER 1
#define I2CCMD_CENTER_COUNTER 2
#define I2CCMD_SET_ADDRESS 3
#define I2CCMD_READ_LASTDIR 5
#define I2CCMD_READ_COUNTER 10


#endif /* TINYQEDI2CCMD_H_ */